services:
  canvas-scraper:
    build:
      context: .
    container_name: canvas-scraper
    image: canvas-scraper:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - TZ=America/New_York
